version: "3.6"
services:
  '711':
    image: someoneelsehere/7elevenpython
    container_name: '711'
    restart: always
    volumes:
      - /docker/711:/config
      - "/etc/localtime:/etc/localtime:ro"
      - /docker/shared:/shared
    ports:
      - "5000:5000"
    environment:
      - TZ="Australia/Sydney"
      - GMAPAPIKEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - BASEURL=https://711-goodcall.api.tigerspike.com/api/v1/
      - PRICEURL=https://projectzerothree.info/api.php?format=json
      - DEVICE_NAME=SM-G973FZKAXSA
      - OS_VERSION="Android 9.0.0"
      - APP_VERSION=1.8.0.2027
